
name: Experiment
on: push

jobs:

  experiment:
    name: Experiment

    runs-on: ubuntu-latest

    steps:
      - name: Experiment
        uses: zpqrtbnk/gh-actions/experiment@master
        
      - name: Infos
        shell: bash
        run: |
          echo "github.ref: '${{ github.ref }}'"
          echo "github.sha: '${{ github.sha }}'"
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report
        shell: bash
        run: |
          set +e
          git log --graph --pretty=format':%h%%d %s %an, %ar' | head -n 5
          echo "--"
          REF="${{ github.ref }}"
          BRANCH=${REF#refs/heads/}
          
          if [ "$BRANCH" != "$REF" ]; then         
            VERSION=${BRANCH#release/}
            if [ "$VERSION" != "$BRANCH" ]; then
                echo "Triggered by commit in version $VERSION release branch $BRANCH"
                git fetch origin wip-$VERSION:wip-$VERSION
                if [ $? -ne 0 ]; then
                    echo "Tag v$VERSION does not exist"
                else
                    TAGSHA=$(git rev-parse wip-$VERSION)
                    echo "FOUND TAG $TAGSHA"
                    if [ "$TAGSHA" != "${{ github.sha }}" ]; then
                        echo "TAG v$VERSION exists on another commit : error"
                        exit 1
                    else
                        echo "Tag v$VERSION exists on this commit: nothing to do here"
                    fi
                fi
            else
                echo "Triggered by commit in non-release branch $BRANCH: error"
                exit 1
            fi
            exit 0
          fi

          TAG=${REF#refs/tags/}
          if [ "$TAG" != "$REF" ]; then
            echo "Triggered by tag $TAG"
            exit 0
          fi
          
          echo "ERR"
          exit 1
