
name: Experiment
on: push

jobs:

  experiment:
    name: Experiment

    runs-on: ubuntu-latest

    steps:
      - name: Experiment
        uses: zpqrtbnk/gh-actions/experiment@master
        
      - name: Infos
        shell: bash
        run: |
          echo "github.ref: '${{ github.ref }}'"
          echo "github.sha: '${{ github.sha }}'"
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report
        shell: bash
        run: |
          set +e
          git log --graph --pretty=format':%h%%d %s %an, %ar' | head -n 5
          echo "--"
          REF="${{ github.ref }}"
          BRANCH=${REF#refs/heads/}
          
          if [ "$BRANCH" != "$REF" ]; then         
            VERSION=${BRANCH#release/}
            if [ "$VERSION" != "$BRANCH" ]; then
                echo "Triggered by commit in version $VERSION release branch $BRANCH"
                git fetch origin refs/tags/v$VERSION:refs/tags/v$VERSION
                if [ $? -ne 0 ]; then
                    echo "Tag v$VERSION does not exist"
                else
                    TAGSHA=$(git rev-parse v$VERSION)
                    echo "FOUND TAG $TAGSHA"
                    if [ "$TAGSHA" != "${{ github.sha }}" ]; then
                        echo "::error::TAG v$VERSION exists on another commit (${{ github.sha }}) : error"
                        exit 1
                    else
                        echo "Tag v$VERSION exists on this commit: nothing to do here"
                    fi
                fi
            else
                echo "::error::Triggered by commit in non-release branch $BRANCH: error"
                exit 1
            fi
            exit 0
          fi

          HZTAG=${REF#refs/tags/}
          if [ "$HZTAG" != "$REF" ]; then
            HZVERSION=${HZTAG#v}
            if [ "$HZVERSION" != "$HZTAG" ]; then # it is a version tag
                echo "Triggered by version tag $HZTAG"
                git fetch origin refs/heads/release/$HZVERSION:refs/heads/release/$HZVERSION
                if [ $? -ne 0 ]; then
                    echo "::error::Branch release/$HZVERSION does not exist"
                    exit 1
                else
                    git tag --contains release/$HZVERSION
                    git log --graph --pretty=format':%h%%d %s %an, %ar' | head -n 5
                    if (git tag --contains release/$HZVERSION | grep -q $HZTAG); then
                        echo "Tag is in the correct branch"
                    else
                        echo "::error::Tag $HZTAG does not belong to branch release/$HZVERSION"
                        exit 1
                    fi
                fi
            else
                echo "::error::Triggered by non-version tag $HZTAG"
                exit 1
            fi
            exit 0
          fi
          
          echo "::error::I am confused"
          exit 1
