
name: Experiment
on: push

jobs:

  experiment:
    name: Experiment

    runs-on: ubuntu-latest

    steps:
      #- name: Experiment
      #  uses: zpqrtbnk/gh-actions/experiment@master
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Invoke
        uses: ./.github/actions/utils
        with:
          mode: meh